# Extends jupyter/datascience-notebook
FROM jupyter/datascience-notebook

# Copies Jupyter notebook used to format restaurant data
COPY FormatRestaurants.ipynb /home/jovyan/FormatRestaurants.ipynb

# Installs pymongo
RUN pip install pymongo